version: '3.8'

services:
  # Servicio de la Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-yqp1rr0d}
      MYSQL_DATABASE: FoodMart
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Servicio de la Aplicación .NET
  app:
    container_name: restaurant_api
    build: .
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=FoodMart;Uid=root;Pwd=${DB_PASSWORD:-yqp1rr0d}
    depends_on:
      - db

volumes:
  mysql-data:
